In [ ]:
# df.shape          # neçə sətir, neçə sütun?
# df.dtypes         # hər sütunun tipi
# df.head(10)       # ilk 10 sətir
# df.tail(5)        # son 5 sətir
# df.sample(5)      # təsadüfi 5 sətir
# df.describe()     # Ümumi statistika
# df.isnull().sum()          # hər sütunda neçə boşluq
# df['species'].value_counts()

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('data/iris.csv')

In [7]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [12]:
df.shape

(150, 5)

In [13]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [17]:
df.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [22]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [23]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [26]:
df.isna().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [38]:

df.sample()

     sepal.length  sepal.width  petal.length  petal.width    variety
135           7.7          3.0           6.1          2.3  Virginica

In [67]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [70]:
df['sepal.length'].max()

np.float64(7.9)

In [71]:
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [72]:
df['variety'].value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

# Tapşırıq

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
# Datasetdə neçə sətir və sütun var?

In [ ]:
# Hər sütunun data tipini yoxla. Hansı sütunlar ədədi, hansılar kateqorikdir?

In [ ]:
# İlk 8 sətrə bax. Sonra təsadüfi 8 sətirə bax.

In [ ]:
# Hansı sütunlarda boş dəyər var? Hər biri üçün neçə boş dəyər olduğunu tap.

In [ ]:
# Age sütunundakı boş dəyərləri sütunun ortalaması ilə doldur.

In [ ]:
# describe() funksiyasını işlət. Age sütununun min, max və ortalama dəyərini tap

In [ ]:
# Survived sütununda neçə nəfər sağ qalmış, neçəsi həlak olmuşdur? Faizlə göstər.

In [ ]:
# Pclass sütununda neçə unikal dəyər var? Hər sinifdən neçə sərnişin var?